"""add_unique_constraints

Revision ID: ee83e2cadf41
Revises: 
Create Date: 2024-11-26 23:11:25.224614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee83e2cadf41'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_film', 'favorite_films', ['user_id', 'film_id'])
    op.create_unique_constraint('uq_user_genre', 'favorite_genres', ['user_id', 'genre_id'])
    op.create_unique_constraint('uq_user_film_viewed', 'viewed', ['user_id', 'film_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_film_viewed', 'viewed', type_='unique')
    op.drop_constraint('uq_user_genre', 'favorite_genres', type_='unique')
    op.drop_constraint('uq_user_film', 'favorite_films', type_='unique')
    # ### end Alembic commands ###
